plugins {
    id 'com.android.application'
}

android {
    namespace 'org.isomorphisms.preferencegym'
    compileSdk 37

    defaultConfig {
        applicationId 'org.isomorphisms.preferencegym'
        minSdk 23
        targetSdk 37
        versionCode 1
        versionName '0.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            java.srcDir 'generated-src'
        }
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.14.0'
}
